FROM golang:1.17 AS builder

# Set the working directory inside the container
WORKDIR /src/
COPY . .

# Build executables
RUN go build -o /app/webapi ./cmd/webapi

# Create final container
FROM debian:bullseye

# Expose ports
EXPOSE 3000 4000

# Copy the build executable from the builder image
WORKDIR /app/
COPY --from=builder /app/webapi ./

# Executable command
CMD ["/app/webapi"]