FROM node:lts as builder

### Copy Vue.js code
WORKDIR /app
COPY webui webui

### Build Vue.js into plain HTML/CSS/JS
### THIS IS JUST FOR THE DEVELOPMENT
WORKDIR /app/webui
RUN yarn install

EXPOSE 5173

CMD ["yarn", "dev", "--host"]