# Use the official Go image
FROM golang:1.19.1

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum, then download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project
COPY . .

# Expose necessary ports for your backend
EXPOSE 3000 4000

# Default command: Run the Go app with `go run` (this is where the hot reloading happens)
CMD ["go", "run", "./cmd/webapi"]
